[package]
name = "compose-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
compose-library = { workspace = true }
compose-syntax = { workspace = true }
compose-error-codes = { workspace = true }
ecow = { workspace = true }
extension-traits = { workspace = true }
tap = {workspace = true}
