[package]
name = "compose-resolve"
version.workspace = true
edition.workspace = true

[dependencies]
indexmap = {workspace = true}
compose-syntax = {workspace = true}
compose-library = {workspace = true}
compose-typeinfo = {workspace = true}
compose-utils= {workspace = true}
fxhash = {workspace = true}
ecow = {workspace = true}

[lints]
workspace = true
