pub mod array;
pub mod bool;
pub mod str;
pub mod func;
pub mod ty;
pub mod int;
pub mod unit;
pub mod boxed;
pub mod range;
pub mod map;

pub use array::{ArrayValue, Array};
pub use func::{Func};
pub use crate::foundations::module::{Module};
pub use ty::{Type, NativeType, NativeTypeData};
pub use unit::{UnitValue};
pub use boxed::Boxed;
pub use range::{RangeValue, Range, RangeImpl};
pub use map::{Map, MapValue};
pub use str::Str;