[package]
name = "compose-doc-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
quote = "1.0.40"
compose-doc = { workspace = true }
unindent = "0.2.4"


[lints]
workspace = true
